### ISSUE TITLE
bootstrap broker required arg?

### ISSUE THREAD

**Issue by ehthayer** [honeycombio/honeykafka#1]
Make a bootstrap broker a required arg rather than bail out with this?

[root@devbox ~]# ./honeykaf -k <mykey> -d metrics.v1
INFO[0000] Starting kh2
panic: kafka: client has run out of available brokers to talk to (Is your cluster reachable?)

goroutine 1 [running]:
github.com/honeycombio/honeykaf/kafkatail.GetChans(0x9ff5a0, 0xc42005c880, 0x7784d9, 0x9, 0x7723f5, 0x4, 0x777e92, 0x8, 0x0, 0x0, ...)
	/home/travis/gopath/src/github.com/honeycombio/honeykaf/kafkatail/kafkatail.go:30 +0x2d5
main.run(0x7a4435, 0x19, 0x0, 0x0, 0x50, 0x64, 0x32, 0x0, 0x3c, 0x0, ...)
	/home/travis/gopath/src/github.com/honeycombio/honeykaf/hk.go:81 +0x329
main.main()
	/home/travis/gopath/src/github.com/honeycombio/honeykaf/main.go:141 +0x336

**Comment by ehthayer** [comment]
or have the kafka broker and port in the error message above

**Comment by bdarfler** [comment]
This project is being sunset; please review issue #13
